version: '3.8'

services:
  db:
    container_name: brain_db
    hostname: brain_db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=${SQL_DATABASE}"
      - "POSTGRES_USER=${SQL_USER}"
      - "POSTGRES_PASSWORD=${SQL_PASSWORD}"
      - "PGDATA=/var/lib/postgresql/data/pgdata"

  backend:
    build:
      context: .
      dockerfile: brain/Dockerfile
    container_name: brain-backend
    command: /start-django
    volumes:
        - ./brain:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
